# Importing TensorFlow

In [ ]:
import tensorflow as tf
tf.__version__

'2.9.2'

# Loading Dataset

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


# Data Preprocessing

In [ ]:
x_train, x_test = x_train/255.0, x_test/255.0

In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_test.shape

(10000, 28, 28)

# Modeling

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

## How to work our model?

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.06204116, -0.31266025, -0.04441132, -0.08686925, -0.29518628,
        -0.06653664,  0.10240483, -0.5198137 , -0.28929704,  0.67983675]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09739793, 0.07580665, 0.09913027, 0.0950095 , 0.07714292,
        0.09696106, 0.11480682, 0.06162282, 0.07759857, 0.20452349]],
      dtype=float32)

## How to work the loss function?

In [ ]:
y_true = [1,2]
y_pred =[[0.05,0.95,0],[0.1,0.8,0.1]]
scce = tf.keras.losses.SparseCategoricalCrossentropy()
scce(y_true, y_pred).numpy()

1.1769392

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.3334458

# Model Compiling

In [ ]:
model.compile(optimizer="adam",
              loss = loss_fn,
              metrics=["accuracy"])

# Model Training

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2986 - accuracy: 0.9124
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1440 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1085 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0888 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0752 - accuracy: 0.9765


# Evaluating the Model

In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0729 - accuracy: 0.9770 - 640ms/epoch - 2ms/step


[0.07287608832120895, 0.9769999980926514]

# Predicting the New Data

In [ ]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [ ]:
predictions = probability_model.predict(x_test[:1])
predictions

1/1 [==============================] - 0s 66ms/step


array([[3.3044097e-07, 2.8835391e-08, 1.1364058e-05, 2.1205934e-04,
        6.3420041e-10, 2.5095582e-07, 2.1806922e-10, 9.9972683e-01,
        4.2633836e-08, 4.9088536e-05]], dtype=float32)

In [ ]:
import numpy as np
np.argmax(predictions[0])

7

In [ ]:
y_test[:1][0]

7