In [1]:
import tensorflow as tf 

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [3]:
(X_train, y_train), (X_test, y_test) = fashion_mnist

In [4]:
X_train, X_test = X_train/255., X_test/255. 

In [5]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", 
               "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [6]:
class_names[y_train[0]]

'Ankle boot'

In [7]:
tf.random.set_seed(42)

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=[28,28]),
    tf.keras.layers.Dense(300, activation="relu"),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(10, activation="softmax")
])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dense_2 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(
    loss = "sparse_categorical_crossentropy",
    optimizer= "sgd", 
    metrics = ["accuracy"]
)

In [11]:
history = model.fit(X_train, y_train, 
                    epochs = 30, 
                    validation_split=0.1)

Epoch 1/30
1688/1688 [==============================] - 10s 4ms/step - loss: 0.7177 - accuracy: 0.7674 - val_loss: 0.5258 - val_accuracy: 0.8162
Epoch 2/30
1688/1688 [==============================] - 5s 3ms/step - loss: 0.4898 - accuracy: 0.8309 - val_loss: 0.5025 - val_accuracy: 0.8223
Epoch 3/30
1688/1688 [==============================] - 5s 3ms/step - loss: 0.4444 - accuracy: 0.8456 - val_loss: 0.4431 - val_accuracy: 0.8437
Epoch 4/30
1688/1688 [==============================] - 6s 4ms/step - loss: 0.4192 - accuracy: 0.8545 - val_loss: 0.4661 - val_accuracy: 0.8263
Epoch 5/30
1688/1688 [==============================] - 6s 4ms/step - loss: 0.3974 - accuracy: 0.8615 - val_loss: 0.4046 - val_accuracy: 0.8543
Epoch 6/30
1688/1688 [==============================] - 7s 4ms/step - loss: 0.3822 - accuracy: 0.8665 - val_loss: 0.4127 - val_accuracy: 0.8543
Epoch 7/30
1688/1688 [==============================] - 5s 3ms/step - loss: 0.3682 - accuracy: 0.8703 - val_loss: 0.3908 - val_accuracy

In [12]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.3316 - accuracy: 0.8838


[0.3315822184085846, 0.8838000297546387]

In [13]:
X_new = X_test[:3]
y_proba = model.predict(X_new)
y_proba.round(2)

1/1 [==============================] - 0s 165ms/step


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.01, 0.  , 0.98],
       [0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],
      dtype=float32)

In [14]:
import numpy as np
y_pred = y_proba.argmax(axis=-1)
y_pred

array([9, 2, 1])

In [16]:
np.array(class_names)[y_pred]

array(['Ankle boot', 'Pullover', 'Trouser'], dtype='<U11')

In [17]:
y_new = y_test[:3]
y_new

array([9, 2, 1], dtype=uint8)